import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import FooterUI from "./__componets/layout/FooterUI";
import Header from "./__componets/layout/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <div className="container mx-auto py-9 md:py-12 px-4 md:px-6">
          {children}
        </div>
        <FooterUI />
      </body>
    </html>
  );
}
