import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarUI from "./__components/layout/NavbarUI";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
        <div className="min-h-full">    
          <NavbarUI />          
          <main>
            <div className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
            {children}
            </div>
          </main>
        </div>          
      </body>
    </html>
  );
}
